Test against more PostgreSQL versions (#86)
* Test against more PostgreSQL versions

* Add an alias to the test subquery

This is required for the query to work in PostgreSQL 15. Otherwise, it
returns:

    ERROR:  subquery in FROM must have an alias